# Generated by Django 5.2.4 on 2025-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielddefinition',
            name='field_type',
        ),
        migrations.AlterField(
            model_name='fieldvalue',
            name='value_type',
            field=models.CharField(choices=[('text', 'Text'), ('binary', 'Binary')], max_length=20),
        ),
    ]
