# Generated by Django 5.2.4 on 2025-07-31 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_api', '0002_remove_fielddefinition_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fielddefinition',
            name='content_type',
        ),
    ]
